In [4]:
# Creating an 1-D array
import numpy as np
x = np.array([1,2,3])
print(x,x.shape)


[1 2 3] (3,)


In [52]:
# Creating an 2-D array
y = np.array([[1,2,3],[4,5,6]])
print(y,y.shape)

[[1 2 3]
 [4 5 6]] (2, 3)


In [53]:
# Creating an 3-D array
z = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(z,z.shape)


[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]] (2, 2, 3)


## ONE DIMENSIONAL ARRAY 


# Insertion

In [54]:
# Inserting a value in the end in 1-D array
x = np.array([1,2,3])
x = np.insert(x,3,4) # x = array name, 3 = index value, 4 = value which you want to add 
print(x)


[1 2 3 4]


In [55]:
x

array([1, 2, 3, 4])

In [5]:
# Inserting a value in the beginning in 1-D array

x = np.array([1,2,3])
x = np.insert(x,0,0)
x

array([0, 1, 2, 3])

# Traversing

In [57]:
for  a in x:
    print(a)

0
1
2
3
4


# Accessing an element of array

In [58]:
print(x[0])
print(x[1])
print(x[2])

0
1
2


# Deleting an element from Array


In [59]:
# create a numpy array
arr = np.array([1, 3, 4, 2, 5])
# remove element at index 2
arr_new = np.delete(arr, 2)
# display the arrays
print("Original array:", arr)
print("After deletion:", arr_new)

Original array: [1 3 4 2 5]
After deletion: [1 3 2 5]


## Two-Dimensional Array


# Insertion

In [60]:
# create a 2-D array
y = np.array([[1,2,3],[4,5,6]])
# inserting a column in the beginning of the array
new_y = np.insert(y,0,[[7,8]],axis = 1)
# inserting a row in the beginning of array
y_3 = np.insert(y,0,[0,1,2],axis=0)
print("orginal array:",y)
print('array after adding a new column in the beginning:', new_y)
print('array after adding a new row in the bginning:', y_3)
#appending a row at the end
y_4 = np.append(y,[[100,101,102]],axis = 0)
print("array after appending a row :", y_4)


orginal array: [[1 2 3]
 [4 5 6]]
array after adding a new column in the beginning: [[7 1 2 3]
 [8 4 5 6]]
array after adding a new row in the bginning: [[0 1 2]
 [1 2 3]
 [4 5 6]]
array after appending a row : [[  1   2   3]
 [  4   5   6]
 [100 101 102]]


# Deleting the row or column

In [61]:
# create a 2-D array
arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
print("Original array:", arr)
# Deleting the 1st row
new_arr = np.delete(arr,0,axis=0)
print("array after deleting 1st row:", new_arr)
#Deleting the 1st column
new_arr_2 = np.delete(arr,0,axis=1)
print("Array after deleting 1st column:", new_arr_2)
# reversing the array
rvr_arr = np.flip(arr)
print("reversed array:", rvr_arr)

Original array: [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
array after deleting 1st row: [[ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Array after deleting 1st column: [[ 2  3  4]
 [ 6  7  8]
 [10 11 12]
 [14 15 16]]
reversed array: [[16 15 14 13]
 [12 11 10  9]
 [ 8  7  6  5]
 [ 4  3  2  1]]


# Slicing

In [62]:
# create a 2-D array
arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
# slicing the arrray
new_arr = arr[1,0:2]
print("original array:", arr)
print("sliced array:", new_arr)

original array: [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
sliced array: [5 6]


### LISTS

In [69]:
# Creating a list
lt = [1,2,3,4,5,6,7,8,9]
print("original list:", lt)
# updating an element in list
lt[0] = 0
print("updated list:", lt)
#Inserting an element to the list
lt.insert(1,1)
print("list after inserting an element :", lt)
# Inserting an element to the end
lt.append(10)
print("appending an element 10 at the end of the list:", lt)
# appending a list at the end of other list
lt.extend([11,12,13])
print("list after appending a list at the end:", lt)


original list: [1, 2, 3, 4, 5, 6, 7, 8, 9]
updated list: [0, 2, 3, 4, 5, 6, 7, 8, 9]
list after inserting an element : [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
appending an element 10 at the end of the list: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
list after appending a list at the end: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]


# List operations and functions

In [88]:
# Creating two list
l1 = [1,2,3]
l2 = [4,5,6]
# concatenating the two list
l3 = l1+l2
print("list 1:", l1)
print("List 2:", l2)
print("Concatenated list:", l3)
# * operator
l4 = l1*3
print(l4)
#FUNCTIONS
#finding the size of list
print("Length of the list 1:", len(l1))
# finding the max value in list
print("Max value in list 1:", max(l1))
print("Max value in list 2:", max(l2))
# finding the min value in a list
print("Min value in list 1:", min(l1))
print("Min value in list 2:", min(l2))
# finding the sum of values in a list
print("Sum of all the values in list 1:", sum(l1))
print("Sum of all the values in list 2:", sum(l2))
# sorting the elements of the list
l1 = [3,7,5,6,9,2]
print("original list l1:", l1)
#method 1
l1.sort()
print("Sorted list l1:", l1)
#method 2
l2 = sorted(l1)
print("sorted list l1:", l2)

list 1: [1, 2, 3]
List 2: [4, 5, 6]
Concatenated list: [1, 2, 3, 4, 5, 6]
[1, 2, 3, 1, 2, 3, 1, 2, 3]
Length of the list 1: 3
Max value in list 1: 3
Max value in list 2: 6
Min value in list 1: 1
Min value in list 2: 4
Sum of all the values in list 1: 6
Sum of all the values in list 2: 15
original list l1: [3, 7, 5, 6, 9, 2]
Sorted list l1: [2, 3, 5, 6, 7, 9]
sorted list l1: [2, 3, 5, 6, 7, 9]


In [78]:
# Converting string to list
s1 = "kuldeep"
l1 = list(s1)
print(l1)

['k', 'u', 'l', 'd', 'e', 'e', 'p']


In [84]:
# Sentence to list of words
s1 = "kuldeep kuldeep kuldeep"
l1 = s1.split()
print(l1)
s2 = "kuldeep-kuldeep-kuldeep"
l2 = s2.split('-')
print(l2)
# Joining words back to form a sentence
print(' '.join(l1))
print("-".join(l2))

['kuldeep', 'kuldeep', 'kuldeep']
['kuldeep', 'kuldeep', 'kuldeep']
kuldeep kuldeep kuldeep
kuldeep-kuldeep-kuldeep
