In [1]:
import numpy as np

array([[0.21034441, 0.55008355],
       [0.98542032, 0.93800719],
       [0.74706939, 0.4626663 ]])

array([[0.5       , 0.6       ],
       [0.21034441, 0.55008355],
       [0.98542032, 0.93800719],
       [0.74706939, 0.4626663 ]])

array([0, None, None, None], dtype=object)

array([None, None, None], dtype=object)